[package]
name = "rusty-bittorrent"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_bytes = "0.11.15"
serde_bencode = "0.2.4"
serde = { version = "1.0.204", features = ["derive"] }

[[bin]]
name = "torrent"
path = "src/main.rs"
